package com.example.util.simpletimetracker.feature_statistics_detail.adapter

import com.example.util.simpletimetracker.feature_base_adapter.buttonsRow.ButtonsRowItemViewData

enum class StatisticsDetailBlock : ButtonsRowItemViewData.ButtonsRowId {
    PreviewItems,
    ChartData,
    ChartDataComparison,
    DailyCalendarHint,
    ChartGrouping,
    ChartLength,
    ChartSplitByActivity,
    ChartSplitByActivitySort,
    RangeAverages,
    Total,
    Average,
    Dates,
    Series,
    SeriesGoal,
    SeriesGoalSelect,
    SeriesChart,
    SeriesChartComparison,
    SeriesType,
    SeriesCalendar,
    SeriesCalendarComparison,
    SeriesCompletion,
    SplitHint,
    SplitChart,
    SplitChartComparison,
    SplitChartGrouping,
    DurationSplitHint,
    DurationSplitChart,
    DurationSplitChartComparison,
    NextActivities,
    GoalStats,
    GoalSelect,
    GoalExcessDeficitHint,
    GoalChartData,
    GoalChartGrouping,
    GoalChartLength,
    GoalRangeAverages,
    GoalTotals,
    TagValuesHint,
    TagValuesChartData,
    TagValuesChartGrouping,
    TagValuesChartLength,
    TagValuesSettings,
    TagValuesRangeAverages,
    TagValuesTotals,
    DataDistributionHint,
    DataDistributionPieChart,
    DataDistributionBarChart,
    DataDistributionMode,
    DataDistributionGraph,
}