package com.example.util.simpletimetracker.feature_statistics_detail.adapter

enum class StatisticsDetailBlock {
    PreviewItems,
    ChartData,
    ChartDataComparison,
    ChartGrouping,
    ChartLength,
    RangeAverages,
    Total,
    Average,
    Dates,
    Series,
    SeriesGoal,
    SeriesChart,
    SeriesChartComparison,
    SeriesType,
    SeriesCalendar,
    SeriesCalendarComparison,
    SeriesCompletion,
    SplitHint,
    SplitChart,
    SplitChartComparison,
    SplitChartGrouping,
    DurationSplitHint,
    DurationSplitChart,
    DurationSplitChartComparison,
    NextActivities,
}