package com.example.util.simpletimetracker.feature_settings.api

enum class SettingsBlock {
    MainTop,
    AllowMultitasking,
    DarkMode,
    Language,
    Categories,
    Archive,
    MainBottom,

    RatingTop,
    RateUs,
    SupportDevelopment,
    Feedback,
    Version,
    DebugMenu,
    RatingBottom,

    NotificationsTop,
    NotificationsCollapse,
    NotificationsShow,
    NotificationsShowControls,
    NotificationsShowEvenWithNoTimers,
    NotificationsInactivity,
    NotificationsInactivityRecurrent,
    NotificationsInactivityDoNotDisturbStart,
    NotificationsInactivityDoNotDisturbEnd,
    NotificationsActivity,
    NotificationsActivityRecurrent,
    NotificationsActivityDoNotDisturbStart,
    NotificationsActivityDoNotDisturbEnd,
    NotificationsSystemSettings,
    NotificationsBottom,

    DisplayTop,
    DisplayCollapse,
    DisplayUntrackedHint,
    DisplayUntrackedInRecords,
    DisplayUntrackedInStatistics,
    DisplayUntrackedIgnoreShort,
    DisplayUntrackedRangeCheckbox,
    DisplayUntrackedRangeStart,
    DisplayUntrackedRangeEnd,
    DisplayCalendarView,
    DisplayReverseOrder,
    DisplayDaysInCalendar,
    DisplayEnabledSearchOnMain,
    DisplayShowActivityFilters,
    DisplayAllowMultipleActivityFilters,
    DisplayShowCategoriesAsPredefinedFilters,
    DisplayEnablePomodoroMode,
    DisplayEnableRepeatButton,
    DisplayRepeatButtonMode,
    DisplayPomodoroModeActivities,
    DisplayGoalsOnSeparateTabs,
    DisplayNavBarAtTheBottom,
    DisplayWidgetBackground,
    DisplayMilitaryFormat,
    DisplayMonthDayFormat,
    DisplayDurationFormat,
    DisplayDurationFormatHint,
    DisplayShowSeconds,
    DisplaySortActivities,
    DisplaySortCategories,
    DisplaySortTags,
    DisplayCustomizeOptionsMenu,
    DisplayCardSize,
    DisplayBottom,

    AdditionalTop,
    AdditionalCollapse,
    AdditionalIgnoreShort,
    AdditionalShowTagSelection,
    AdditionalTagSelectionExcludeActivities,
    AdditionalCloseAfterOneTag,
    AdditionalCloseAfterOneTagExcludeActivities,
    AdditionalShowCommentInput,
    AdditionalCommentInputExcludeActivities,
    AdditionalKeepStatisticsRange,
    AdditionalRetroactiveTrackingMode,
    AdditionalKeepScreenOn,
    AdditionalStartTimerByLongClick,
    AdditionalFirstDayOfWeek,
    AdditionalShiftStartOfDay,
    AdditionalShiftStartOfDayButton,
    AdditionalShiftStartOfDayHint,
    AdditionalAutomatedTracking,
    AdditionalSendEvents,
    AdditionalDataEdit,
    AdditionalComplexRules,
    AdditionalActivitySuggestions,
    AdditionalBottom,

    BackupTop,
    BackupCollapse,
    BackupSave,
    BackupAutomatic,
    BackupAutomaticHint,
    BackupAutomaticTime,
    BackupRestore,
    BackupCustomized,
    BackupCustomizedPartialSave,
    BackupCustomizedFullRestore,
    BackupCustomizedPartialRestore,
    BackupCustomizedTriggerAutoBackup,
    BackupBottom,

    ExportTop,
    ExportCollapse,
    ExportSpreadsheet,
    ExportSpreadsheetAutomatic,
    ExportSpreadsheetAutomaticHint,
    ExportSpreadsheetAutomaticTime,
    ExportSpreadsheetDateTimeFormat,
    ExportSpreadsheetDateTimeFormatHint,
    ExportSpreadsheetImport,
    ExportSpreadsheetImportHint,
    ExportIcs,
    ExportCustomized,
    ExportTriggerAutoBackup,
    ExportBottom,

    TranslatorsTop,
    TranslatorsTitle,
    TranslatorsBottom,

    ContributorsTop,
    ContributorsTitle,
    ContributorsBottom,

    PomodoroFocusTime,
    PomodoroBreakTime,
    PomodoroLongBreakTime,
    PomodoroPeriodsUntilLongBreak,
    PomodoroShowMoreControls,

    CustomizeOptionsMenuRecordsCalendar,
    CustomizeOptionsMenuRecordsFilter,
    CustomizeOptionsMenuRecordsShare,
    CustomizeOptionsMenuRecordsBackToToday,
    CustomizeOptionsMenuRecordsSelectDate,

    CustomizeOptionsMenuStatisticsFilter,
    CustomizeOptionsMenuStatisticsShare,
    CustomizeOptionsMenuStatisticsBackToToday,
    CustomizeOptionsMenuStatisticsSelectDate,
    CustomizeOptionsMenuStatisticsSelectRange,

    CustomizeOptionsMenuDetailedStatisticsCompare,
    CustomizeOptionsMenuDetailedStatisticsFilter,
    CustomizeOptionsMenuDetailedStatisticsSelectDate,
    CustomizeOptionsMenuDetailedStatisticsSelectRange,
    CustomizeOptionsMenuDetailedStatisticsBackToToday,
}