[versions]
gradle = "8.4.0"
kotlin = "1.9.25"
ktlint = "12.1.0"
ksp = "1.9.25-1.0.20" # same as kotlin
marathon = "0.10.3"

coroutines = "1.6.4"
nanohttpd = "2.3.1"
timber = "4.7.1"
javax = "1"

appcompat = "1.7.0"
constraintLayout = "2.1.4"
recyclerView = "1.3.2"
room = "2.6.1"
dagger = "2.52"
viewpager2 = "1.0.0"
flexBox = "3.0.0"
services = "18.0.0"
gson = "2.10.1"
desugaring = "1.1.6"
cardView = "1.0.0"
material = "1.12.0"
emoji = "1.5.0"
wearInput = "1.2.0-alpha02"

fragmentKtx = "1.6.2" # 1.8.2 breaks shared transition when deleting running record.
coreKtx = "1.2.0"
liveDataCoreKtx = "2.8.4"
liveDataKtx = "2.8.4"
viewModelKtx = "2.8.4"
navigationKtx = "2.5.3"
activityKtx = "1.8.2"

compose_version = "1.3.1"
wear_compose_version = "1.2.1"
compose_icons = "1.6.1"
wear_compose_tooling_preview = "1.0.0"
horologist = "0.2.7"
compose_kotlin_compiler = "1.5.15"
compose_hilt = "1.0.0"
wear_complications = "1.2.1"
wear_ongoing = "1.0.0"
metadata_jvm = "0.5.0"

junit = "4.13"
junitUi = "1.1.4"
espresso = "3.5.0"
mockito = "5.14.2"
mockitoKotlin = "5.4.0"
coroutinesTest = "1.7.1"
rules = "1.5.0"

[libraries]
kotlin = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlin" }
coroutines = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines" }
javax = { group = "javax.inject", name = "javax.inject", version.ref = "javax" }
nanohttpd = { module = "org.nanohttpd:nanohttpd", version.ref = "nanohttpd" }
timber = { group = "com.jakewharton.timber", name = "timber", version.ref = "timber" }

# Androidx
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-constraintLayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintLayout" }
androidx-recyclerView = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerView" }
androidx-room = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
androidx-viewpager2 = { group = "androidx.viewpager2", name = "viewpager2", version.ref = "viewpager2" }
androidx-cardView = { group = "androidx.cardview", name = "cardview", version.ref = "cardView" }
androidx-material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-wear-input = { group = "androidx.wear", name = "wear-input", version.ref = "wearInput" }

# Google
google-dagger = { group = "com.google.dagger", name = "hilt-android", version.ref = "dagger" }
google-flexBox = { group = "com.google.android.flexbox", name = "flexbox", version.ref = "flexBox" }
google-services = { group = "com.google.android.gms", name = "play-services-wearable", version.ref = "services" }
google-gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
google-desugaring = { group = "com.android.tools", name = "desugar_jdk_libs", version.ref = "desugaring" }

# Emoji
emoji-emojiBundled = { group = "androidx.emoji2", name = "emoji2-bundled", version.ref = "emoji" }

# Ktx
ktx-core = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
ktx-fragment = { group = "androidx.fragment", name = "fragment-ktx", version.ref = "fragmentKtx" }
ktx-liveDataCore = { group = "androidx.lifecycle", name = "lifecycle-livedata-core-ktx", version.ref = "liveDataCoreKtx" }
ktx-liveData = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "liveDataKtx" }
ktx-viewModel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "viewModelKtx" }
ktx-room = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
ktx-navigationFragment = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigationKtx" }
ktx-navigationUi = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "navigationKtx" }
ktx-activity = { group = "androidx.activity", name = "activity-ktx", version.ref = "activityKtx" }

# Compose
compose-activity = { group = "androidx.activity", name = "activity-compose", version.ref = "compose_version" }
compose-ui = { group = "androidx.compose.ui", name = "ui", version.ref = "compose_version" }
compose-uiToolingPreview = { group = "androidx.compose.ui", name = "ui-tooling-preview", version.ref = "compose_version" }
compose-materialIcons = { group = "androidx.compose.material", name = "material-icons-core", version.ref = "compose_icons" }
compose-wearNavigation = { group = "androidx.wear.compose", name = "compose-navigation", version.ref = "wear_compose_version" }
compose-wearMaterial = { group = "androidx.wear.compose", name = "compose-material", version.ref = "wear_compose_version" }
compose-wearFoundation = { group = "androidx.wear.compose", name = "compose-foundation", version.ref = "wear_compose_version" }
compose-wearToolingPreview = { group = "androidx.wear", name = "wear-tooling-preview", version.ref = "wear_compose_tooling_preview" }
compose-horologist = { group = "com.google.android.horologist", name = "horologist-compose-layout", version.ref = "horologist" }
compose-horologistComposables = { group = "com.google.android.horologist", name = "horologist-composables", version.ref = "horologist" }
compose-hilt = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "compose_hilt" }
compose-uiTooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "compose_version" }

# Wear
wear-complications = { group = "androidx.wear.watchface", name = "watchface-complications-data-source-ktx", version.ref = "wear_complications" }
wear-wearOngoing = { group = "androidx.wear", name = "wear-ongoing", version.ref = "wear_ongoing" }

# Kapt
kapt-room = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
kapt-dagger = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "dagger" }
kapt-metadata = { group = "org.jetbrains.kotlinx", name = "kotlinx-metadata-jvm", version.ref = "metadata_jvm" }

# Test
test-junit = { group = "junit", name = "junit", version.ref = "junit" }
test-mockito = { group = "org.mockito", name = "mockito-core", version.ref = "mockito" }
test-mockitoKotlin = { group = "org.mockito.kotlin", name = "mockito-kotlin", version.ref = "mockitoKotlin" }
test-coroutines = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "coroutinesTest" }

# UiTest
uitest-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitUi" }
uitest-espresso = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso" }
uitest-espressoContrib = { group = "androidx.test.espresso", name = "espresso-contrib", version.ref = "espresso" }
uitest-espressoIdling = { group = "androidx.test.espresso", name = "espresso-idling-resource", version.ref = "espresso" }
uitest-dagger = { group = "com.google.dagger", name = "hilt-android-testing", version.ref = "dagger" }
uitest-room = { group = "androidx.room", name = "room-testing", version.ref = "room" }
uitest-rules = { group = "androidx.test", name = "rules", version.ref = "rules" }

[plugins]
gradleApplication = { id = "com.android.application", version.ref = "gradle" }
gradleLibrary = { id = "com.android.library", version.ref = "gradle" }
kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" } # short "kotlin-android"
kotlinLibrary = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" } # short "kotlin"
kotlinParcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" } # short "kotlin-parcelize"
javaLibrary = { id = "java-library" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "dagger" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
marathon = { id = "com.malinskiy.marathon", version.ref = "marathon" }