package com.example.util.simpletimetracker

object Versions {
    const val gradle = "8.2.0"
    const val kotlin = "1.8.22"
    const val ktlint = "12.1.0"

    const val coroutines = "1.6.4"
    const val timber = "4.7.1"
    const val javax = "1"

    const val appcompat = "1.7.0"
    const val constraintLayout = "2.1.4"
    const val recyclerView = "1.1.0"
    const val room = "2.4.3"
    const val dagger = "2.52"
    const val viewpager2 = "1.0.0"
    const val flexBox = "3.0.0"
    const val services = "18.0.0"
    const val gson = "2.10.1"
    const val desugaring = "1.1.6"
    const val cardView = "1.0.0"
    const val material = "1.8.0"
    const val emoji = "1.4.0"

    const val fragmentKtx = "1.8.2"
    const val coreKtx = "1.2.0"
    const val liveDataCoreKtx = "2.8.4"
    const val liveDataKtx = "2.8.4"
    const val viewModelKtx = "2.8.4"
    const val navigationKtx = "2.5.3"
    const val activityKtx = "1.8.2"

    const val compose_version = "1.3.1"
    const val wear_compose_version = "1.2.1"
    const val compose_icons = "1.6.1"
    const val wear_compose_tooling_preview = "1.0.0"
    const val horologist = "0.2.7"
    const val compose_kotlin_compiler = "1.4.8"
    const val compose_hilt = "1.0.0"
    const val wear_complications = "1.2.1"
    const val wear_ongoing = "1.0.0"
    const val metadata_jvm = "0.5.0"

    const val junit = "4.13"
    const val junitUi = "1.1.4"
    const val espresso = "3.5.0"
    const val mockito = "5.2.0"
    const val coroutinesTest = "1.7.1"
}