package com.example.util.simpletimetracker.core.viewData

enum class SettingsBlock {
    MainTop,
    AllowMultitasking,
    DarkMode,
    Language,
    Categories,
    Archive,
    DataEdit,
    MainBottom,

    RatingTop,
    RateUs,
    Feedback,
    Version,
    RatingBottom,

    NotificationsTop,
    NotificationsCollapse,
    NotificationsShow,
    NotificationsShowControls,
    NotificationsInactivity,
    NotificationsInactivityRecurrent,
    NotificationsInactivityDoNotDisturb,
    NotificationsActivity,
    NotificationsActivityRecurrent,
    NotificationsActivityDoNotDisturb,
    NotificationsBottom,

    DisplayTop,
    DisplayCollapse,
    DisplayUntrackedHint,
    DisplayUntrackedInRecords,
    DisplayUntrackedInStatistics,
    DisplayUntrackedIgnoreShort,
    DisplayUntrackedRange,
    DisplayCalendarView,
    DisplayReverseOrder,
    DisplayDaysInCalendar,
    DisplayShowActivityFilters,
    DisplayGoalsOnSeparateTabs,
    DisplayKeepScreenOn,
    DisplayWidgetBackground,
    DisplayMilitaryFormat,
    DisplayMonthDayFormat,
    DisplayProportionalFormat,
    DisplayShowSeconds,
    DisplaySortActivities,
    DisplayCardSize,
    DisplayBottom,

    AdditionalTop,
    AdditionalCollapse,
    AdditionalIgnoreShort,
    AdditionalShowTagSelection,
    AdditionalCloseAfterOneTag,
    AdditionalShowWithOnlyGeneral,
    AdditionalKeepStatisticsRange,
    AdditionalFirstDayOfWeek,
    AdditionalRepeatButton,
    AdditionalShiftStartOfDay,
    AdditionalShiftStartOfDayHint,
    AdditionalAutomatedTracking,
    AdditionalSendEvents,
    AdditionalBottom,

    BackupTop,
    BackupCollapse,
    BackupSave,
    BackupAutomatic,
    BackupAutomaticHint,
    BackupRestore,
    BackupBottom,

    ExportTop,
    ExportCollapse,
    ExportSpreadsheet,
    ExportSpreadsheetAutomatic,
    ExportSpreadsheetAutomaticHint,
    ExportSpreadsheetImport,
    ExportSpreadsheetImportHint,
    ExportIcs,
    ExportBottom,
}